apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: exam
  labels:
    type: local
spec:
  storageClassName: mongodb-storageclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
